- src/components/project/projectCard/projectCard.tsx
- src/components/project/projectTable/projectTable.tsx
- src/components/project/projectTabs/projectTabs.tsx
fix api responce of project 
and run lint-fix
> fix api responce and run lint-fix

- src/app/admin/page.tsx
- src/components/Admin/addAdmin.tsx
- src/components/Admin/adminTable.tsx
- src/components/Notification/notifyTable.tsx
- src/config/menuItems/admin/dashboardMenuItems.tsx
- src/utils/common/enum.ts
DF-42  make admin table/page
and fix delete notification api
> DF-42 make admin table/page -Abhi

- src/components/Faq/addFaq.tsx
- src/components/freelancer/table/FreelancerTable.tsx
- src/services/apiService.tsx
- src/services/example.tsx
- src/utils/common/enum.ts
- Create service folder
- Add base api service
- Add 1 example entity service
- Add 1 get and 1 post example and replace in codebase
> DF-50: Create API service in dehix_admin_frontend

- src/app/auth/login/page.tsx
- src/config/menuItems/admin/dashboardMenuItems.tsx
Corrected path for landing page after login
Fixed side bar path for business table
path -: src\app\auth\login\page.tsx
src\config\menuItems\admin\dashboardMenuItems.tsx
> Df-86: hot fix admin login landing page and sidebar fixing for business page

- src/components/Domain/addDomain.tsx
- src/components/Domain/domainTable.tsx
- src/utils/common/enum.ts
Changes made according to the comments and new api
path :
src\app\domain
src\components\Domain
> Df 27: created domain table with new api and resolved comments

- src/app/business/tabs/page.tsx
- src/app/skill/page.tsx
- src/components/business/businessInfo/appliedCandidates.tsx
- src/components/business/businessInfo/hireCandidates.tsx
- src/components/business/businessInfo/personalInfo.tsx
- src/components/business/businessInfo/professionalInfo.tsx
- src/components/business/businessInfo/projectList.tsx
- src/components/skill/addskill.tsx
- src/components/skill/skillTable.tsx
Redesigned the business table page 
path 
src\components\business\businessInfo
src\app\business
> DF-92: Redesigned the business table page corrected the overflowing of the data 

- src/app/projectdomain/page.tsx
- src/components/ProjectDomain/addProjectDomain.tsx
- src/components/ProjectDomain/projectdomainTable.tsx
- src/components/business/table/BusinessTable.tsx
- src/services/domain.tsx
- src/services/projectdomain.tsx
- src/utils/common/enum.ts
Created project domain table where user may change the status of domain and add new domain
path:
src/app/projectdomain
src/components/ProjectDomain
src/services/projectdomain
> Df-102: Created project domain table

- src/components/ProjectDomain/addProjectDomain.tsx
- src/components/ProjectDomain/projectdomainTable.tsx
changed the traversal and change of the status values.
> Df-102:changed the status change to array indexing

- src/components/Domain/addDomain.tsx
- src/components/Domain/domainTable.tsx
- src/components/skill/addskill.tsx
- src/components/skill/skillTable.tsx
- src/services/domain.tsx
- src/services/skill.tsx
changed the traversal for skill and domain table
> Df 117: changed the traversal in skill and domain table

- src/app/bid/page.tsx
- src/config/menuItems/admin/dashboardMenuItems.tsx
> DF-120: Add icon to dangling table

- .eslintrc.json
- src/components/Admin/adminTable.tsx
- src/components/Domain/domainTable.tsx
- src/components/Faq/faqTable.tsx
- src/components/Notification/notifyTable.tsx
- src/components/business/table/BusinessTable.tsx
- src/components/freelancer/table/FreelancerTable.tsx
- src/components/project/projectTable/projectTable.tsx
- src/components/ui/skeleton.tsx
> add skelton on admin pages

- src/components/freelancer/freelancer-info/tabs/personalinfoCards/personalinfoCards.tsx
- src/components/freelancer/freelancer-info/tabs/professionalInfo/professionalinfoCard.tsx
- src/components/freelancer/freelancer-info/tabs/talent/talentCards.tsx
Edited color of the texts in freelancer tabs for light mode and changed the github icon in social links.
> DF- 138 Edited color of the texts in freelancer tabs for light mode 

- src/components/Domain/domainTable.tsx
- src/components/ProjectDomain/projectdomainTable.tsx
- src/components/bid/bidtable.tsx
- src/components/business/businessInfo/hireCandidates.tsx
- src/components/copybutton.tsx
- src/components/freelancer/freelancer-info/tabs/skillDomain/skillDomain.tsx
- src/components/interview/Interviewtable.tsx
- src/components/skill/skillTable.tsx
- src/utils/common/enum.ts
added copy button and format id to every id with tooltip
> Df 126:added copy button and format id to every id in table

- src/components/Admin/addAdmin.tsx
- src/components/Admin/adminTable.tsx
- src/components/Domain/domainTable.tsx
- src/components/Faq/addFaq.tsx
- src/components/Faq/faqTable.tsx
- src/components/Notification/addNotify.tsx
- src/components/Notification/notifyTable.tsx
- src/components/bid/bidtable.tsx
- src/components/business/businessInfo/appliedCandidates.tsx
- src/components/business/businessInfo/hireCandidates.tsx
- src/components/business/businessInfo/personalInfo.tsx
- src/components/business/businessInfo/professionalInfo.tsx
- src/components/business/table/BusinessTable.tsx
- src/components/freelancer/freelancer-info/tabs/project/project.tsx
- src/components/freelancer/freelancer-info/tabs/skillDomain/skillDomain.tsx
- src/components/freelancer/table/FreelancerTable.tsx
- src/components/project/projectTable/projectTable.tsx
- src/services/faq.tsx
- src/services/notification.tsx
added toast to every page of the admin dashboard
> Df 141:added toast to every page in admin

- src/app/business/tabs/page.tsx
- src/components/business/businessInfo/appliedCandidates.tsx
- src/components/business/businessInfo/hireCandidates.tsx
- src/components/business/businessInfo/personalInfo.tsx
- src/components/business/businessInfo/professionalInfo.tsx
changed the display of business details
changed the api call and sent the data through props
> Df 129-: changed form data in business and changed verification data

- src/components/skill/skillTable.tsx
added format time in the skill table
> Df 124 added format time to skill table

- src/components/dash-comp/talentForm/skilldomainForm.tsx
- src/components/dialogs/addProject.tsx
- src/components/form/businessCreateProjectForm.tsx
- src/components/form/profileForm.tsx
- src/components/skill/addskill.tsx
- src/services/admin.tsx
- src/services/bid.tsx
- src/services/business.tsx
- src/services/domain.tsx
- src/services/faq.tsx
- src/services/freelancer.tsx
- src/services/interview.tsx
- src/services/notification.tsx
- src/services/projectdomain.tsx
- src/services/skill.tsx
> api name changing

- src/components/freelancer/freelancer-info/tabs/educationalInfo/educationalInfo.tsx
- src/components/freelancer/freelancer-info/tabs/personalinfoCards/personalinfoCards.tsx
- src/components/freelancer/freelancer-info/tabs/professionalInfo/professionalinfoCard.tsx
- src/components/freelancer/freelancer-info/tabs/professionalProjects/professionalProjects.tsx
- src/components/freelancer/freelancer-info/tabs/talent/talentCards.tsx
- src/utils/common/utils.ts
Added this icon-:
Also changed this to text-:
> Df156-: check for handling data in freelancer

- src/components/ProjectDomain/projectdomainTable.tsx
- src/services/projectdomain.tsx
- src/utils/common/enum.ts
integrated API for status change and changed path for api
> DF-159: Integrated api in project domain

- src/components/Admin/adminTable.tsx
- src/components/confirmationDialog.tsx
- src/utils/common/utils.ts
> DF-164: Added pop up when deleting admin

- src/components/menu/sidebarMenu.tsx
- src/config/menuItems/admin/dashboardMenuItems.tsx
> DF-161 Add a verification sidebar and change the formatting of sidebar  

- src/components/Domain/domainTable.tsx
- src/components/Domain/editDomaindesc.tsx
- src/services/domain.tsx
> Sp-63: Added feature to change the description of domain

- next.config.mjs
- src/components/Notification/addNotify.tsx
- src/components/Notification/notifyTable.tsx
- src/utils/common/enum.ts
> DF-160: Add s3 image in notification table

- src/components/business/table/BusinessTable.tsx
- src/components/dropdown.tsx
- src/services/business.tsx
- src/services/project.tsx
- src/utils/common/enum.ts
- src/utils/common/utils.ts
> Sp3-66:Added feature to change the account status 

- src/components/Notification/addNotify.tsx
- src/components/skill/addskill.tsx
- src/components/skill/editSkilldesc.tsx
- src/components/skill/skillTable.tsx
- src/services/skill.tsx
- src/utils/common/enum.ts
> SP3-102: Added edit description in skill

- .husky/pre-commit
> harshit/added pre-commit

- next-env.d.ts
- package-lock.json
- package.json
- src/components/bid/bidtable.tsx
Modified Bid Description Page
Modified UI:
> Updated bid table #80
